version: "3"
services:
  service:
    build: .
    image: q-server
    ports:
      - 8080:8080 # external port : internal port
    env_file:
      - config.env # config file
    volumes:
      - type: bind
        source: assets/ # relative path where schema.sqlite is stored
        target: /app/data
    networks:
      - service-network
networks:
  service-network:
